#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinCRMAndroid.Resource", IsApplication=true)]

namespace XamarinCRMAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::XamarinCRMAndroid.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::XamarinCRMAndroid.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::XamarinCRMAndroid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::XamarinCRMAndroid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::XamarinCRMAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int accent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int primary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int windowBackground = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_android_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_android_gray = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_android = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bottom_up_gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int map_marker_android = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int phone_android = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int xamarin_logo_plus_name_inline = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int agentWebView = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int axisLayout = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int chartAreaLayout = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int chartTitle = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int dataMarkerLayout = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int gridLineLayout = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int iconView = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int label = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int legendHeader = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int legendItemsLayout = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int legendScrollView = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int legendViewGroup = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int rootLayout = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int seriesLayout = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int stripLinesLayout = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chart_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_legend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int webauthenticationbroker = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int GoogleMapsKey = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060004
			public const int AppTheme = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int XamarinCRMTheme = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int XamarinCRMTheme_ActionBar_TitleTextStyle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int XamarinCRMTheme_ActionBarStyle = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int XamarinCRMTheme_Base = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
