// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace XamarinCRM {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XamarinCRM.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MainTabs_Sales {
            get {
                return ResourceManager.GetString("MainTabs_Sales", resourceCulture);
            }
        }
        
        internal static string MainTabs_Customers {
            get {
                return ResourceManager.GetString("MainTabs_Customers", resourceCulture);
            }
        }
        
        internal static string MainTabs_Products {
            get {
                return ResourceManager.GetString("MainTabs_Products", resourceCulture);
            }
        }
        
        internal static string MainTabs_About {
            get {
                return ResourceManager.GetString("MainTabs_About", resourceCulture);
            }
        }
        
        internal static string Splash_UsernameTitleLabel {
            get {
                return ResourceManager.GetString("Splash_UsernameTitleLabel", resourceCulture);
            }
        }
        
        internal static string Splash_PasswordTitleLabel {
            get {
                return ResourceManager.GetString("Splash_PasswordTitleLabel", resourceCulture);
            }
        }
        
        internal static string Splash_SignIn {
            get {
                return ResourceManager.GetString("Splash_SignIn", resourceCulture);
            }
        }
        
        internal static string Splash_SkipSignIn {
            get {
                return ResourceManager.GetString("Splash_SkipSignIn", resourceCulture);
            }
        }
        
        internal static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string Exit_and_Discard {
            get {
                return ResourceManager.GetString("Exit_and_Discard", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string Get_Directions {
            get {
                return ResourceManager.GetString("Get_Directions", resourceCulture);
            }
        }
        
        internal static string Leave_Application {
            get {
                return ResourceManager.GetString("Leave_Application", resourceCulture);
            }
        }
        
        internal static string NetworkConnection_Alert_Title {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Title", resourceCulture);
            }
        }
        
        internal static string NetworkConnection_Alert_Message {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Message", resourceCulture);
            }
        }
        
        internal static string NetworkConnection_Alert_Confirm {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Confirm", resourceCulture);
            }
        }
        
        internal static string NoPosition_Alert_Title {
            get {
                return ResourceManager.GetString("NoPosition_Alert_Title", resourceCulture);
            }
        }
        
        internal static string NoPosition_Alert_Message {
            get {
                return ResourceManager.GetString("NoPosition_Alert_Message", resourceCulture);
            }
        }
        
        internal static string NoPosition_Alert_Confirm {
            get {
                return ResourceManager.GetString("NoPosition_Alert_Confirm", resourceCulture);
            }
        }
        
        internal static string Leads_LeadListHeaderTitle {
            get {
                return ResourceManager.GetString("Leads_LeadListHeaderTitle", resourceCulture);
            }
        }
        
        internal static string Leads_NewLead {
            get {
                return ResourceManager.GetString("Leads_NewLead", resourceCulture);
            }
        }
        
        internal static string Leads_EditLead {
            get {
                return ResourceManager.GetString("Leads_EditLead", resourceCulture);
            }
        }
        
        internal static string Leads_SaveConfirmTitle {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Leads_SaveConfirmDescription {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Leads_ExitConfirmTitle {
            get {
                return ResourceManager.GetString("Leads_ExitConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Leads_ExitConfirmDescription {
            get {
                return ResourceManager.GetString("Leads_ExitConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunityHeading {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunityHeading", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_CompanyName {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_CompanyName", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_CompanyNamePlaceholder {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_CompanyNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_Industry {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_Industry", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunitySize {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunitySize", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunitySizePlaceholder {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunitySizePlaceholder", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunityStage {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunityStage", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_SaveButtonText {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_SaveButtonText", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Role {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Role", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_FirstName {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_FirstName", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_LastName {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_LastName", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Phone {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Phone", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Email {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Email", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Address {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Address", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_PostalCode {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_PostalCode", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_City {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_City", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_State {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_State", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Country {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Country", resourceCulture);
            }
        }
        
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        internal static string SalesDashboard_SalesChart_Header_Title {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_Header_Title", resourceCulture);
            }
        }
        
        internal static string SalesDashboard_SalesChart_Header_WeeklyAverageTitle {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_Header_WeeklyAverageTitle", resourceCulture);
            }
        }
        
        internal static string SalesDashboard_SalesChart_LoadingLabel {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_LoadingLabel", resourceCulture);
            }
        }
        
        internal static string SalesDashboard_Leads_LoadingLabel {
            get {
                return ResourceManager.GetString("SalesDashboard_Leads_LoadingLabel", resourceCulture);
            }
        }
        
        internal static string SalesDashboard_SalesChart_PrimaryAxis_Title {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_PrimaryAxis_Title", resourceCulture);
            }
        }
        
        internal static string SalesDashboard_SalesChart_YAxis_Title {
            get {
                return ResourceManager.GetString("SalesDashboard_SalesChart_YAxis_Title", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Detail_Tab_Title", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Orders_Tab_Title", resourceCulture);
            }
        }
        
        internal static string Customers_Sales_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Sales_Tab_Title", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_Address {
            get {
                return ResourceManager.GetString("Customers_Detail_Address", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_NewOrder {
            get {
                return ResourceManager.GetString("Customers_Orders_NewOrder", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_Save {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_Save", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_BackButton {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_BackButton", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_CompanyTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_CompanyTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_NewOrderTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_NewOrderTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_ProductTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ProductTitleLabel", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_PriceTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_PriceTitleLabel", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_OrderDateTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OrderDateTitleLabel", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_DueDateTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DueDateTitleLabel", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_ClosedDateTitleLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ClosedDateTitleLabel", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_ProductEntryPlaceholder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ProductEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_PriceEntryPlaceholder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_PriceEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_DueDateEntryPlaceholder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DueDateEntryPlaceholder", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_AddToOrder {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_AddToOrder", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_SaveConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_SaveConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_SaveConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_SaveConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_ExitConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ExitConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_ExitConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_ExitConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_OkayConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OkayConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_OrderItemNotSelectedConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OrderItemNotSelectedConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_OrderItemNotSelectedConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_OrderItemNotSelectedConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_DeliverConfirmTitle {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DeliverConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_DeliverConfirmDescription {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DeliverConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_DeliverConfirmAffirmative {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_DeliverConfirmAffirmative", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_EditOrder_LoadingImageLabel {
            get {
                return ResourceManager.GetString("Customers_Orders_EditOrder_LoadingImageLabel", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_CustomerTabbedPage_BackToCustomers {
            get {
                return ResourceManager.GetString("Customers_Orders_CustomerTabbedPage_BackToCustomers", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_MappingDirections_LeaveApplication {
            get {
                return ResourceManager.GetString("Customers_Detail_MappingDirections_LeaveApplication", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_MappingDirections_LeaveApplication_Yes {
            get {
                return ResourceManager.GetString("Customers_Detail_MappingDirections_LeaveApplication_Yes", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_CallDialog_Title {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Title", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_CallDialog_Message {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Message", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_CallDialog_Accept {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Accept", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_CallDialog_Cancel {
            get {
                return ResourceManager.GetString("Customers_Detail_CallDialog_Cancel", resourceCulture);
            }
        }
        
        internal static string Customers_OrderOpen {
            get {
                return ResourceManager.GetString("Customers_OrderOpen", resourceCulture);
            }
        }
        
        internal static string Customers_OrderClosed {
            get {
                return ResourceManager.GetString("Customers_OrderClosed", resourceCulture);
            }
        }
        
        internal static string Customer_Order_Detail_Deliver_Order {
            get {
                return ResourceManager.GetString("Customer_Order_Detail_Deliver_Order", resourceCulture);
            }
        }
        
        internal static string Customer_Sales_By_Category_Header {
            get {
                return ResourceManager.GetString("Customer_Sales_By_Category_Header", resourceCulture);
            }
        }
        
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        internal static string Products_CategoryList_LoadingLabel {
            get {
                return ResourceManager.GetString("Products_CategoryList_LoadingLabel", resourceCulture);
            }
        }
        
        internal static string Products_ProductList_LoadingLabel {
            get {
                return ResourceManager.GetString("Products_ProductList_LoadingLabel", resourceCulture);
            }
        }
    }
}
