// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MobileCRM.Localization {
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class TextResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (Equals(null, resourceMan)) {
                    ResourceManager temp = new ResourceManager("MobileCRM.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SalesChartHeaderWeeklyAverageTitle {
            get {
                return ResourceManager.GetString("SalesChartHeaderWeeklyAverageTitle", resourceCulture);
            }
        }
        
        internal static string Leads_SaveConfirmTitle {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        internal static string Leads_EditLead {
            get {
                return ResourceManager.GetString("Leads_EditLead", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string SalesChartHeaderTitle {
            get {
                return ResourceManager.GetString("SalesChartHeaderTitle", resourceCulture);
            }
        }
        
        internal static string Leads_NewLead {
            get {
                return ResourceManager.GetString("Leads_NewLead", resourceCulture);
            }
        }
        
        internal static string Leads_SaveConfirmDescription {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Leads_LeadListHeaderTitle {
            get {
                return ResourceManager.GetString("Leads_LeadListHeaderTitle", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
    }
}
