// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System.Reflection;

namespace MobileCRM.Localization {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobileCRM.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SalesChartHeaderWeeklyAverageTitle {
            get {
                return ResourceManager.GetString("SalesChartHeaderWeeklyAverageTitle", resourceCulture);
            }
        }
        
        internal static string Leads_SaveConfirmTitle {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        internal static string Leads_EditLead {
            get {
                return ResourceManager.GetString("Leads_EditLead", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string SalesChartHeaderTitle {
            get {
                return ResourceManager.GetString("SalesChartHeaderTitle", resourceCulture);
            }
        }
        
        internal static string Leads_NewLead {
            get {
                return ResourceManager.GetString("Leads_NewLead", resourceCulture);
            }
        }
        
        internal static string Leads_SaveConfirmDescription {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Leads_LeadListHeaderTitle {
            get {
                return ResourceManager.GetString("Leads_LeadListHeaderTitle", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
    }
}
