// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MobileCRM {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobileCRM.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Leads_SaveConfirmDescription {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmDescription", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunitySizePlaceholder {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunitySizePlaceholder", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_City {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_City", resourceCulture);
            }
        }
        
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunityStage {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunityStage", resourceCulture);
            }
        }
        
        internal static string Leads_EditLead {
            get {
                return ResourceManager.GetString("Leads_EditLead", resourceCulture);
            }
        }
        
        internal static string Leads_NewLead {
            get {
                return ResourceManager.GetString("Leads_NewLead", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_SaveButtonText {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_SaveButtonText", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Country {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Country", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Address {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Address", resourceCulture);
            }
        }
        
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Detail_Tab_Title", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Role {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Role", resourceCulture);
            }
        }
        
        internal static string MainTabs_Sales {
            get {
                return ResourceManager.GetString("MainTabs_Sales", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_FirstName {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_FirstName", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Phone {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Phone", resourceCulture);
            }
        }
        
        internal static string Customers_Sales_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Sales_Tab_Title", resourceCulture);
            }
        }
        
        internal static string SalesChartHeaderWeeklyAverageTitle {
            get {
                return ResourceManager.GetString("SalesChartHeaderWeeklyAverageTitle", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_CompanyNamePlaceholder {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_CompanyNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string Leads_LeadListHeaderTitle {
            get {
                return ResourceManager.GetString("Leads_LeadListHeaderTitle", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunitySize {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunitySize", resourceCulture);
            }
        }
        
        internal static string MainTabs_Customers {
            get {
                return ResourceManager.GetString("MainTabs_Customers", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_PostalCode {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_PostalCode", resourceCulture);
            }
        }
        
        internal static string Leads_SaveConfirmTitle {
            get {
                return ResourceManager.GetString("Leads_SaveConfirmTitle", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_Industry {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_Industry", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_Email {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_Email", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_OpportunityHeading {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_OpportunityHeading", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_LastName {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_LastName", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string Customers_Detail_Address {
            get {
                return ResourceManager.GetString("Customers_Detail_Address", resourceCulture);
            }
        }
        
        internal static string Leads_LeadDetail_CompanyName {
            get {
                return ResourceManager.GetString("Leads_LeadDetail_CompanyName", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_NewOrder {
            get {
                return ResourceManager.GetString("Customers_Orders_NewOrder", resourceCulture);
            }
        }
        
        internal static string MainTabs_Products {
            get {
                return ResourceManager.GetString("MainTabs_Products", resourceCulture);
            }
        }
        
        internal static string SalesChartHeaderTitle {
            get {
                return ResourceManager.GetString("SalesChartHeaderTitle", resourceCulture);
            }
        }
        
        internal static string Customers_Orders_Tab_Title {
            get {
                return ResourceManager.GetString("Customers_Orders_Tab_Title", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Leads_LeadContactDetail_State {
            get {
                return ResourceManager.GetString("Leads_LeadContactDetail_State", resourceCulture);
            }
        }
    }
}
